# Generated by Django 5.0.1 on 2024-03-05 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yolov8", "0002_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["created_at"]},
        ),
    ]
