# Generated by Django 5.0.1 on 2024-03-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yolov8", "0004_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="file_name",
            field=models.CharField(default="abc.xlsx", max_length=50),
        ),
    ]
